### ISSUE TITLE
Implement Alembic for Database Migrations

### ISSUE THREAD

**Issue by avb7** [NamanSudan/blogFrog#19]
# Introduction to Alembic Database Migrations

In software development, particularly in web applications that involve databases, the structure of the database (also known as the database schema) can change over time as the application's requirements evolve. Manually applying these changes to a live database can be error-prone, difficult to manage, and hard to reproduce consistently across different environments (development, testing, staging, production). 

Alembic is a database migration tool for SQLAlchemy and it's designed to handle changes in the database schema. It allows us to alter our database schema and apply changes in a manner similar to a version control system. This makes the project more robust and the changes easier to manage.

This issue will track the integration of Alembic into our Flask application, blogFrog. It involves setting up Alembic, generating the initial migration (based on our current `models.py` file), and updating our README with the new information.

## Steps to Implement Alembic

1. **Install Alembic:** 

   Install Alembic via pip and add it to `requirements.txt`.

2. **Initialize Alembic:** 

This command will create a new `alembic` directory in our project, with a couple of files to get us started. 
```
pip install alembic
```
Add alembic to your requirements.txt after running the command above.

3. **Configure Alembic:** 

Update the `alembic.ini` and `env.py` file to configure Alembic for our project.

In `alembic.ini`, set the `sqlalchemy.url` to the same SQLALCHEMY_DATABASE_URI from our Flask configuration (refer to the `.env` for these details).

In `env.py`, replace the `target_metadata` variable with our models' MetaData.

```python
from flask import current_app
config.set_main_option('sqlalchemy.url', current_app.config.get('SQLALCHEMY_DATABASE_URI'))
target_metadata = current_app.extensions['migrate'].db.metadata
```

## 1. Generate Initial Migration:

Use the revision command to generate a new migration file. The --autogenerate flag will fill in the migration with our current models from models.py.

```
alembic revision --autogenerate -m "Initial migration"
```

## 2. Apply Migrations:

Use the upgrade command to apply the migrations to the database.

```
alembic upgrade head
```

Please commit the new alembic directory (except for alembic.ini which contains sensitive information), the alembic.ini with placeholders, and the updated requirements.txt file to the repository.

Finally, update the README.md file with the information about setting up and running migrations with Alembic, and the importance of keeping track of the database schema changes.

**Comment by NamanSudan** [comment]
Correction needed in this instruction page. Step 2's line of code is incorrect. Should be:
alembic init alembic

**Comment by NamanSudan** [comment]
**Need support** with **Generate Initial Migration**. Getting the error:
`blogfrog-d.csy5l8zjy5t3.us-east-1.rds.amazonaws.com could not be translated to an address.`

Upon doing some research, some of the possible reasons for this could be:

1. Incorrect Hostname: There might be a typo or error in your host name. Check the host name to ensure it's correct.

2. DNS Resolution Issue: The error could be due to a DNS resolution issue. This could happen if the DNS server that's being used can't resolve the host name to an IP address. To resolve this, you could try to use the direct IP address of your database if possible. Or you can verify the DNS settings of your machine or network.

3. Network Connectivity Issue: There could be a network connectivity issue. You should check if you can reach the database from your current location or not. You can use ping or telnet in the command line to check this.

4. Database Connectivity Issue: The database might not be running or it might not be accessible from your current location due to firewall rules or other network security configurations. Verify that the database is running and that your current network is allowed to access it.

**Comment by NamanSudan** [comment]
> **Need support** with **Generate Initial Migration**. Getting the error: `blogfrog-d.csy5l8zjy5t3.us-east-1.rds.amazonaws.com could not be translated to an address.`
> 
> Upon doing some research, some of the possible reasons for this could be:
> 
> 1. Incorrect Hostname: There might be a typo or error in your host name. Check the host name to ensure it's correct.
> 2. DNS Resolution Issue: The error could be due to a DNS resolution issue. This could happen if the DNS server that's being used can't resolve the host name to an IP address. To resolve this, you could try to use the direct IP address of your database if possible. Or you can verify the DNS settings of your machine or network.
> 3. Network Connectivity Issue: There could be a network connectivity issue. You should check if you can reach the database from your current location or not. You can use ping or telnet in the command line to check this.
> 4. Database Connectivity Issue: The database might not be running or it might not be accessible from your current location due to firewall rules or other network security configurations. Verify that the database is running and that your current network is allowed to access it.

Fixed this but now getting a different error

**Comment by NamanSudan** [comment]
Getting this error:

Traceback (most recent call last):
  File "/Users/namansudan/Library/Python/3.9/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/command.py", line 236, in revision
    script_directory.run_env()
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/namansudan/Library/Python/3.9/lib/python/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic/env.py", line 24, in <module>
    config.set_main_option('sqlalchemy.url', create_app.config.get('SQLALCHEMY_DATABASE_URI'))
AttributeError: 'function' object has no attribute 'config'

**Comment by NamanSudan** [comment]
> 

Already have added app context to try to mitigate this issue but still getting the same error

**Comment by NamanSudan** [comment]
Fixed those errors. Output for Generate Initial Migration: 
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'post_id_seq' as owned by integer column 'post(id)', assuming SERIAL and omitting
INFO  [alembic.autogenerate.compare] Detected removed table 'post'
  Generating /Users/namansudan/Desktop/blogging_platform/alembic/versions/e1b02ebc833c_initial_migration.py ...  done

I don't understand the **INFO  [alembic.autogenerate.compare] Detected removed table 'post'** because it implies that the post table has been removed compared to the state of the database when the last migration was run. Since this is the first migration & we have the Post table in our database, then this message shouldn't have appeared. 

What to do?
